[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.111.3"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[redirects]]
from = "/bsky"
to = "https://bsky.app/profile/did:plc:tnjzjt2e3o4w7oxyh3cedqsq/lists/3lcc4gw2asl2c"
status = 302
